# Generated by Django 3.0.5 on 2020-08-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userdata_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEncData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('phone', models.CharField(max_length=130)),
                ('email', models.CharField(max_length=130)),
                ('userid', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
